### PR TITLE
Documentation text clarifications and grammar and typo fixes

### PR DESCRIPTION
**Pull request by stewx**

### CODE REVIEW

**Comment by stewx** [comment]
@wycats Can you take a look?

**Comment by stewx** [comment]
@kpdecker Can you take a look?

**Comment by stewx** [comment]
@nknapp can you take a look? This PR has been open for almost a year and is for minor changes

**Comment by nknapp** [comment]
Thanks for pointing this out. That really were a lot of issues. I've merged the PR, and I might be able to update the site tonight, but this is not an automatic process yet, so the changes will not appear on the site right away.

**Comment by nknapp** [comment]
I have built a new site, but changes seem to be cached a little longer than usual. I haven't seen any updates to the site yet, but I'm sure they will come.

**Pull request merged**
